name = "sidecar-c"

[[auxflash.blobs]]
file = "drv/sidecar-mainboard-controller/sidecar_mainboard_controller_rev_c.bit"
compress = true
tag = "FPGA"

[[auxflash.blobs]]
file = "drv/sidecar-front-io/sidecar_qsfp_x32_controller_rev_b_c.bit"
compress = true
tag = "QSFP"
