name = "sidecar-b"
board = "sidecar-b"
inherit = "base.toml"

[[auxflash.blobs]]
file = "drv/sidecar-mainboard-controller/sidecar_mainboard_controller_rev_b.bit"
compress = true
tag = "FPGA"

[[auxflash.blobs]]
file = "drv/sidecar-front-io/sidecar_qsfp_x32_controller_rev_b_c.bit"
compress = true
tag = "QSFP"
