[package]
name = "drv-monorail-api"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-idol-err = { path = "../../lib/derive-idol-err" }
userlib = { path = "../../sys/userlib" }
vsc7448 = { path = "../vsc7448" }
vsc85xx = { path = "../vsc85xx" }

hubpack.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true

[features]
# Allow the technician port to talk to every SP, instead of just upstream to the
# Scrimlet.  This is the default in -lab and -bench builds, but is not allowed
# in production.
technician-port-override = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false

[build-dependencies]
idol.workspace = true
