name = "rot-carrier"
target = "thumbv8m.main-none-eabihf"
board = "rot-carrier-2"
chip = "../../chips/lpc55"
memory = "memory_stage1_hack_a.toml"
image-names = ["stage1_a"]
external-images = ["a"]


[kernel]
name = "stage0"
requires = {flash = 0x9000, ram = 16000}
#features = ["dice-self"]
stacksize = 14000

[tasks.idle]
name = "task-idle"
priority = 0
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[signing]
enable-secure-boot = true
enable-dice = true
dice-inc-nxp-cfg = false
dice-cust-cfg = false
dice-inc-sec-epoch = false

[[signing.certs]]
cert-paths = ["../../support/fake_certs/fake_certificate.der.crt"  ]
priv-key = "../../support/fake_certs/fake_private_key.pem"
