[package]
name = "task-attest"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true

lib-dice = { path = "../../lib/dice" }
ringbuf = { path = "../../lib/ringbuf" }
stage0-handoff = { path = "../../lib/stage0-handoff" }
attest-api = { path = "../attest-api" }
unwrap-lite = { path = "../../lib/unwrap-lite" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
anyhow.workspace = true
idol.workspace = true
serde.workspace = true

build-util = { path = "../../build/util" }

[[bin]]
name = "task-attest"
test = false
bench = false
