[package]
name = "task-udprpc"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = { workspace = true }

task-net-api = { path = "../net-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = { path = "../../build/util" }

[features]
# The Hubris build system only allows us to add features when doing inheritance
# of TOML files.  In addition, we want the base `app.toml` to be our production
# image.  Given these constraints, `udprpc` is disabled unless the `enable`
# feature is set.
enable = []
vlan = ["task-net-api/vlan"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-udprpc"
test = false
bench = false
