[[flash]]
name = "a"
address = 0x00020000
size = 0x30000
read = true
execute = true

[[flash]]
name = "b"
address = 0x00060000
size = 0x30000
read = true
execute = true

[[flash]]
name = "stage0"
address = 0x00000000
size = 0x10000
read = true
execute = true

[[flash]]
name = "dice-mfg"
address = 0x90000
size = 0x800
read = true
write = false
execute = false

[[ram]]
name = "a"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "b"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "stage0"
address = 0x20000000
size = 0x4000
read = true
write = true
execute = false

# Info about the images loaded into flash and dumped by stage0 into USB SRAM
# for hubris use.
[[sram3]]
name = "a"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false

[[sram3]]
name = "b"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false

[[sram3]]
name = "stage0"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
