[[flash]]
name = "a"
address = 0x00010000
size = 0x40000
read = true
execute = true

[[flash]]
name = "b"
address = 0x00050000
size = 0x40000
read = true
execute = true

[[flash]]
name = "stage0"
address = 0x00000000
size = 0x10000
read = true
execute = true

[[flash]]
name = "dice-mfg"
address = 0x90000
size = 0x800
read = true
write = false
execute = false

[[ram]]
name = "a"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "b"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "stage0"
address = 0x20000000
size = 0x4000
read = true
write = true
execute = false

[[sram2]]
name = "a"
address = 0x20020000
size = 0x10000
read = true
write = true
execute = false
dma = true

[[sram2]]
name = "b"
address = 0x20020000
size = 0x10000
read = true
write = true
execute = false
dma = true

[[sram2]]
name = "stage0"
address = 0x20020000
size = 0x10000
read = true
write = true
execute = false
dma = true

# Info about the images loaded into flash and dumped by stage0 into USB SRAM
# for hubris use.
[[usbsram]]
name = "a"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
dma = true

[[usbsram]]
name = "b"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
dma = true

[[usbsram]]
name = "stage0"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
dma = true

