name = "gimletlet"
target = "thumbv7em-none-eabihf"
board = "gimletlet-2"
chip = "../../chips/stm32h7"
memory = "memory-large.toml"
stacksize = 896
epoch = 0
version = 0

[kernel]
name = "gimletlet"
requires = {flash = 32768, ram = 8192}

[caboose]
region = "flash"
size = 256
default = true

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 16384, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536
notifications = ["fault", "timer"]
extern-regions = ["sram2", "sram3", "sram4"]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
max-sizes = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3", "system_flash"]
start = true
task-slots = ["jefe"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32h7"]
priority = 5
max-sizes = {flash = 2048, ram = 1024}
start = true
task-slots = ["sys"]
notifications = ["timer"]

[tasks.pong]
name = "task-pong"
priority = 8
max-sizes = {flash = 1024, ram = 1024}
start = true
task-slots = ["user_leds"]
notifications = ["timer"]

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "gpio"]
priority = 7
max-sizes = {flash = 32768, ram = 32768}
stacksize = 2048
start = true
task-slots = ["sys", "user_leds"]

[tasks.net]
name = "task-net"
stacksize = 6040
priority = 3
features = ["h753", "vlan", "gimletlet-nic", "use-spi-core", "spi4"]
max-sizes = {flash = 131072, ram = 65536, sram1 = 16384}
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma", "tim16", "spi4"]
start = true
task-slots = ["sys", "jefe"]
notifications = ["eth-irq", "mdio-timer-irq", "spi-irq", "wake-timer"]

[tasks.net.interrupts]
"eth.irq" = "eth-irq"
"tim16.irq" = "mdio-timer-irq"
"spi4.irq" = "spi-irq"

[tasks.busywait]
name = "task-busywait"
priority = 2
max-sizes = {flash = 8192, ram = 1024}
start = true

[tasks.udpecho_slowly]
name = "task-udpecho-slowly"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net", "busywait"]
features = ["vlan"]
notifications = ["socket"]

[tasks.idle]
name = "task-idle"
priority = 9
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.port_e]
outputs = [
    {port = "E", pins = [12, 14], af = 5},
]
input = {port = "E", pin = 13, af = 5}

[config.spi.spi4.devices.spi4_header]
mux = "port_e"
cs = [{port = "E", pin = 11}]

[config.net]
vlan = { start = 0x301, count = 2 }
# UDP ports in sockets below are assigned in oxidecomputer/oana

[config.net.sockets.echo_slowly]
kind = "udp"
owner = {name = "udpecho_slowly", notification = "socket"}
port = 7777
tx = { packets = 10, bytes = 1024 }
rx = { packets = 10, bytes = 1024 }
