[package]
name = "attest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
gateway-messages = { workspace = true }
hubpack = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
zerocopy = { workspace = true }

derive-idol-err = { path = "../../lib/derive-idol-err" }
userlib = {  path = "../../sys/userlib", features = ["panic-messages"]  }

[build-dependencies]
idol = { workspace = true }
serde = { workspace = true }

[lib]
test = false
bench = false
