name = "demo-stm32h753-nucleo"
target = "thumbv7em-none-eabihf"
board = "nucleo-h753zi"
chip = "../../chips/stm32h7"
memory = "memory-large.toml"
stacksize = 896

[kernel]
name = "demo-stm32h7-nucleo"
requires = {flash = 24000, ram = 5120}
features = ["h753"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 16384, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
max-sizes = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3", "system_flash"]
start = true
task-slots = ["jefe"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32h7"]
priority = 2
max-sizes = {flash = 2048, ram = 1024}
start = true
task-slots = ["sys"]
notifications = ["timer"]

[tasks.pong]
name = "task-pong"
priority = 3
max-sizes = {flash = 1024, ram = 1024}
start = true
task-slots = ["user_leds"]
notifications = ["timer"]

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "gpio"]
priority = 5
max-sizes = {flash = 32768, ram = 32768 }
stacksize = 2048
start = true
task-slots = ["sys"]

[tasks.net]
name = "task-net"
stacksize = 6000
priority = 3
max-sizes = {flash = 131072, ram = 32768, sram1 = 32768}
features = ["h753"]
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma", "tim16"]
start = true
notifications = ["eth-irq", "mdio-timer-irq", "wake-timer"]
task-slots = ["sys", "jefe"]

[tasks.net.interrupts]
"eth.irq" = "eth-irq"
"tim16.irq" = "mdio-timer-irq"

[tasks.busywait]
name = "task-busywait"
priority = 2
max-sizes = {flash = 8192, ram = 1024}
start = true

[tasks.udpecho_slowly]
name = "task-udpecho-slowly"
priority = 4
max-sizes = {flash = 32768, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net", "busywait"]
notifications = ["socket"]

[tasks.idle]
name = "task-idle"
priority = 7
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config.net]
# UDP ports in sockets below are assigned in oxidecomputer/oana

[config.net.sockets.echo_slowly]
kind = "udp"
owner = {name = "udpecho_slowly", notification = "socket"}
port = 7777
tx = { packets = 10, bytes = 1024 }
rx = { packets = 10, bytes = 1024 }
