[package]
name = "drv-gimlet-apcb-server"
version = "0.1.0"
edition = "2021"

[dependencies]
crc.workspace = true
hubpack.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
serde.workspace = true
stm32h7.workspace = true
zerocopy.workspace = true

drv-gimlet-apcb-api = { path = "../gimlet-apcb-api" }
drv-gimlet-hf-api = { path = "../gimlet-hf-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
#amd-apcb = { git = "ssh://git@github.com/oxidecomputer/amd-apcb.git", tag = "v0.1.1", features = [], default-features = false }
amd-apcb = { path = "../../../amd-apcb", features = [], default-features = false }

[build-dependencies]
build-util = {path = "../../build/util"}
idol = { workspace = true }

[features]
#host_access = []
#hash = []
#h743 = ["stm32h7/stm32h743", "drv-stm32xx-sys-api/h743", "drv-stm32h7-qspi/h743"]
#h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753", "drv-stm32h7-qspi/h753"]
