[package]
name = "drv-busywait-api"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
zerocopy.workspace = true
userlib.path = "../../sys/userlib"

[build-dependencies]
idol.workspace = true

[lib]
name = "drv_busywait_api"
test = false
bench = false
