[package]
name = "task-busywait"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
num-traits.workspace = true
idol-runtime.workspace = true
zerocopy.workspace = true

[build-dependencies]
idol.workspace = true

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-busywait"
test = false
bench = false
