name: release
on:
  workflow_call:
    inputs:
      machine:
        description: "Machine we are releasing for"
        required: true
        type: string
      build:
        description: "Machine we are releasing for"
        required: true
        type: string
      app_name:
        description: "Machine we are releasing for"
        required: true
        type: string
      app_toml:
        description: "Machine we are releasing for"
        required: true
        type: string
      target:
        description: "Machine we are releasing for"
        required: true
        type: string
      image:
        description: "Machine we are releasing for"
        required: true
        type: string
            
      
jobs:
  do-build:
    uses: ./.github/workflows/build-one.yml
    with:
       build: ${{ inputs.build }}
       app_name: ${{ inputs.app_name }}
       app_toml: ${{ inputs.app_toml }}
       target: ${{ inputs.target }}
       image: ${{ inputs.image }}
       os: ubuntu-latest

  release-build:
    needs: do-build
    runs-on: ubuntu-latest
    steps:
    - name: grab binary
      id: grab
      uses: actions/download-artifact@v3
      with:
        name: dist-ubuntu-latest-${{ inputs.build }}
        path: out
    - name: Do release things
      run: |
        VERSION=$(cut -d/ -f3- <<< "$GITHUB_REF")
        echo a
        echo $VERSION
        echo b
        echo ${{ inputs.machine }}
        for build in `ls ${{ steps.grab.outputs.download-path }}`; do
           mv $build `basename $build .zip`-$VERSION.zip
        done
        ls ${{ steps.grab.outputs.download-path }}
        #echo ${{ steps.grab.outputs.download-path }}
        #md5sum dist-ubuntu-latest-${{ inputs.build }}.zip
