name: release-builds
on:
  push:
    branches:
      - "test-rot-*"
      - "test-gimlet-*"

jobs:
  release-rot:
    uses: ./.github/workflows/release.yml
    with:
      machine: oxide-rot-1
      build: oxide-rot-1
      app_name: oxide-rot-1
      app_toml: app/oxide-rot-1/app.toml
      target: thumbv8m.main-none-eabihf
      image: "a, b"

    
