name: release
on:
  workflow_call:
    inputs:
      set:
        description: "Which set to build"
        required: true
        type: string

jobs:
  do-build:
    uses: ./.github/workflows/build-sp.yml
    with:
       os: ubuntu-latest
       system: ${{ inputs.set }}

  release-build:
    needs: do-build
    runs-on: ubuntu-latest
    steps:
    - name: grab binary
      id: grab
      uses: actions/download-artifact@v3
      with:
        path: out
    - name: prep
      run: |
        #VERSION=$(cut -d/ -f3- <<< "$GITHUB_REF")
        #VERSION=`echo $VERSION | awk -F- '{print $NF}'`
        VERSION=v3.3.3
        OUT=${{ steps.grab.outputs.download-path }}
        ls $OUT
        for build in `ls $OUT`; do
           for f in `ls $OUT/build`; do
              mv $OUT/$build $OUT/`basename $build .zip`-$VERSION.zip
           done
        done
        ls $OUT

    - name: cut release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          ${{ steps.grab.outputs.download-path }}/*.zip
