name: release-builds
on:
  push:
    tags:
      - "oxide-rot-1*"
      - "gimlet-*"
      - "psc-*"
      - "sidecar-*"
    branches:
      - "testing-*"

jobs:
  release-stuff:
    if: startsWith(github.ref, 'refs/heads/testing')
    uses: ./.github/workflows/release.yml
    with:
      board-set: psc


