name: release
on:
  push:
    branches:
      - "test-rot-*"
      - "test-gimlet-*"
            
      
jobs:
  release-build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Echo test
      run: |
        VERSION=$(cut -d/ -f3- <<< "$GITHUB_REF")
        echo a
        echo $VERSION
        echo b
        echo ${{ inputs.name }}
