name: release
on:
  workflow_call:
    inputs:
      machine:
        description: "Machine we are releasing for"
        required: true
        type: string
            
      
jobs:
  release-build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Echo test
      run: |
        VERSION=$(cut -d/ -f3- <<< "$GITHUB_REF")
        echo a
        echo $VERSION
        echo b
        echo ${{ inputs.machine }}
